python3 -m src.train \
  --trainer grpo \
  --train_jsonl ./offline_data/data.jsonl \
  --output_dir outputs/ \
  --model meta-llama/Llama-3.1-8B-Instruct \
  --epochs 2 \
  --save_every 50 \
  --per_device_batch_size 1 \
  --grad_accum_steps 32 \
  --lr 5e-5 \
  --log_every 5
