python3 -m src.train \
  --trainer sft \
  --train_jsonl ./offline_data/data.jsonl \
  --init_adapter outputs/grpo/ \
  --output_dir outputs/sft_llama_8B \
  --model meta-llama/Llama-3.1-8B-Instruct \
  --epochs 3 \
  --per_device_batch_size 1 \
  --grad_accum_steps 8 \
  --lr 1e-4 \
  --save_every 40 \
  --max_completion_tokens 768